### PR TITLE
Move list of timezones into its own file

### PR DESCRIPTION
**Pull request by leonardehrenfried**
So that it's not repeated for each version.

I'm actually not sure if this syntax is correct but Github Actions and Intellij seem to understand it.

@testower @hannesj @PierrickP Do you know if it's going to work?

### CODE REVIEW

**Comment by testower** [comment]
@leonardehrenfried I can test it locally with my java model generator

**Comment by PierrickP** [comment]
I need to check if [ajv lib](https://ajv.js.org/) handle `$ref` !

**Comment by testower** [comment]
I have confirmed that this will work with some effort with our java model generator (https://github.com/entur/gbfs-java-model). I'm not certain about our java validator (https://github.com/entur/gbfs-validator-java) - it requires some more digging, which will have to wait a bit. It uses this library to load schemas and perform the validation logic: https://github.com/everit-org/json-schema (similar to ajv for javascript).

**Comment by PierrickP** [comment]
I just tested on the MobilityData's validator.
Out of the box, it's not working, because we load schema individually.
I tried, it's possible to add additional schema to use the `$ref` keyword !

Even with the small fix, it's not working.
I'm not sure of the validity of the`"$ref": "../common/timezones.json#/definitions/timezone"`.
I tried with `"$ref": "https://data.iana.org/time-zones/tzdb-2022c/#/definitions/timezone"`, 
`https://data.iana.org/time-zones/tzdb-2022c/` is the `$id` of the timezone file and `definitions/timezone` the path to the schema, and AJV correctly retrieve the schema (see https://ajv.js.org/guide/combining-schemas.html#a-name-ref-a-combining-schemas-with-ref)

Finally, maybe I won't make a common folder, but one per version, to keep a total separation between.

**Comment by leonardehrenfried** [comment]
Ok, do think that it's something that I should pursue or is it perhaps not worth the extra effort and complexity? @PierrickP @testower

**Comment by testower** [comment]
My gut feeling right now says maybe not worth it

**Comment by PierrickP** [comment]
I will vote for the continuation :D 
Especially since the listing of time zones is an indigestible enum. 

@isabelle-dr as schema writer, what is your feeling ?

**Comment by testower** [comment]
If the tooling supports it and it makes schema maintenance easier, then by all means, I will not oppose it :)

**Comment by isabelle-dr** [comment]
Hey all, 

I don't have a strong feeling about this, but here are my thoughts.
The solution proposed by @leonardehrenfried is definitely more elegant, and it makes _some_ maintenance easier (if a modification needs to be made with the list of timezones - which I don't expect to happen more than once a year = 15min won if it needs to be changed in one file only VS all), but sometimes simplicity prevails.
This requires an additional piece in the validator, and it makes the GBFS Json Schema _a little_ harder to use, I think. 

You are the experts, I would go with your opinions here. 
@AntoineAugusti do you have thoughts here?

**Comment by AntoineAugusti** [comment]
This seems elegant! I'd say let's do it if it's not too much trouble to adapt dependencies and load subschemas. Loading a JSON Schema made by IANA as @PierrickP tried seems like a good idea as well.

**Comment by isabelle-dr** [comment]
@testower, shall we try then?

**Comment by testower** [comment]
Well, selfishly I would say no to this right now because it creates work for me to support this in my own toolset. I'm unsure if the added complexity is worth it, even if it looks more elegant, given how infrequently these will be updated.

**Comment by isabelle-dr** [comment]
Okay, let's not go down this track right now. There are probably other JSON Schema users that would have the same POV as @testower (additional work in their toolset).

@leonardehrenfried, thanks for the initiative 🙏, let's keep this in mind and re-open the discussion if we hear that this long enum makes it frustrating to use the Schemas.

**Comment by leonardehrenfried** [comment]
That's understandable.

If the management of these lists becomes annoying we can pick this up again.

They change so rarely that I suspect it won't.

**Comment by richfab** [comment]
Closing this PR as consensus was reached not to pursue this change for now. Feel free to reopen when needed. Thanks!

**Pull request closed without merging**
