### PR TITLE
Update list of tz database time zones

### PR DESCRIPTION
**Pull request by richfab**
Fixes https://github.com/MobilityData/gbfs-json-schema/issues/146

This PR updates the list of time zones in the schemas (v2.0 to v3.1-RC) with the content of the `TZ identifier` column from https://en.wikipedia.org/wiki/List_of_tz_zones.

All existing time zones in the schemas were preserved as they all existed in https://en.wikipedia.org/wiki/List_of_tz_zones. 

As a result, schemas are more permissive than before and all feeds that were valid are still valid ✅ 

🇨🇦 For example, 'America/Montreal' is now considered valid by the GBFS JSON Schemas.

### CODE REVIEW

**Comment by richfab** [comment]
@davidgamez What is needed for the GBFS validator to use these changes?

**Comment by richfab** [comment]
Example of [validation](https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fquebec.publicbikesystem.net%2Fcustomer%2Fgbfs%2Fv2%2Fgbfs.json%09) with the feed from àVélo Quebec (the time zone 'America/Montreal' should be accepted):
image

**Comment by richfab** [comment]
cc @Alessandro100 who worked on improving the JSON Schema import in the GBFS validator, if I remember correctly.

**Comment by davidgamez** [comment]
> @davidgamez What is needed for the GBFS validator to apply these changes?
We must deploy the GBFS validator as the JSON-schema is packaged during building time.

**Comment by richfab** [comment]
I triggered a "Clear cache and deploy site" on Netlify for the GBFS validator but it's still using the previous version of the JSON Schemas. Can the dev team help please? Thanks! 🙏

**Comment by davidgamez** [comment]
> I triggered a "Clear cache and deploy site" on Netlify for the GBFS validator but it's still using the previous version of the JSON Schemas. Can the dev team help please? Thanks! 🙏

Sorry, I was not clear enough. We need to deploy using GitHub actions. Let me create a PR for it.

**Pull request merged**
